version: '3'

services:
  
  mysql:
    image: mysql:5.7
    container_name: helpin-db-v1
    ports:
      - "3306:3306"
    volumes:
      - /data/mysql:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: ${DB_ALLOW_EMPTY_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}

  web:
    build: .
    container_name: helpin-api-v1
    ports:
      - "3333:3333"
    restart: always
    volumes:
      - ./:/app
    links:
      - mysql
    depends_on:
      - mysql